"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import BottomNav from "@/components/BottomNav";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Maharashtra Tours Travels",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Maharashtra Tours Travels</title>
        <meta name="description" content="Description" />
      </head>
      <body className={inter.className}>
        <div className="sticky top-0 bg-bgSecondary">
          <Navbar />
        </div>
        <div className="bg-bgSecondary">{children}</div>
        {/* Mobile */}
        <div className="md:hidden block sticky bottom-0">
          <BottomNav />
        </div>
      </body>
    </html>
  );
}
